### PR TITLE
ER: Hardened Docker Build. 

### PR DESCRIPTION
**Pull request by cofin**
This PR has a number of changes:
- Config is now a Python dataclass
- Gunicorn is now installed with api-requirements.  Flask executes through Gunicorn in the container.
- Mutli-staged docker build.  Runtime environment has limited packages and no build packages (reduced attack surface)
- Code is namespaced under `db_assessment` module.
- Removed unused imports and sorted imports
- Spelling corrections

### CODE REVIEW

**Comment by cofin** [comment]
After the latest round of edits, I have been able to execute this locally as well as submit a manual Cloud Run build.  Removing the draft status on the PR.

**Comment by a200462790** [comment]
LGTM

**Review by ersantosnet — APPROVED** [review]
Thanks Cody!

**Pull request merged**
