### PR TITLE
ER: Execute scripts from project root & Remove unused scripts

### PR DESCRIPTION
**Pull request by cofin**
Update the scripts to allow for executing in the project root.

Remove scripts that are no longer part of the execution process.

### CODE REVIEW

**Review by wpuziewicz — APPROVED** [review]
Tested the load process with the updated code.  Look good.

**Comment by cofin** [comment]
This is ready to be merged once the next approval comes in.

**Comment by smpawar** [comment]
LGTM

**Review by smpawar — APPROVED** [review]
LGTM

**Pull request merged**
